import Head from "next/head";
import styles from "@/styles/Home.module.css";
import buttonStyles from "../styles/buttons.module.css";
import { useUser } from "@auth0/nextjs-auth0/client";
import React from "react";
import NavigationMenu from "../components/navigation";
import Playground from "../components/playground";
import Diversity2Icon from "@mui/icons-material/Diversity2";

export default function Home() {
  const { user, error, isLoading } = useUser();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.appWrapper}>
          <NavigationMenu isAuthenticated={!!user?.sub} />

          {!!user?.sub ? (
            <Playground />
          ) : (
            <div className={styles.description}>
              <div className={styles.bodyText}>
                <div className="logo">
                  <a role="button" href="#">
                    <Diversity2Icon />
                  </a>
                </div>
                <div className="auth-required-message">
                  <h4 className="message-header">Authentication Required</h4>
                  <div className="message-body">Please log in to access this page</div>
                </div>
                <div className="auth-buttons">
                  <a href={"/api/auth/login"} className={`${buttonStyles.btn} ${buttonStyles.btnSmall}`}>
                    <span className="btn-label-wrapper">
                      <span className="btn-label-inner">Log in</span>
                    </span>
                  </a>
                  <a href={"/api/auth/login"} className={`${buttonStyles.btn} ${buttonStyles.btnSmall}`}>
                    <span className="btn-label-wrapper">
                      <span className="btn-label-inner">Sign up</span>
                    </span>
                  </a>
                </div>
              </div>

              <style jsx>
                {`
                  a .material-symbols-outlined {
                    font-size: 36px;
                    color: var(--gray-600);
                  }

                  h4 {
                    padding: 8px;
                  }

                  .auth-required-message {
                    margin-bottom: 1em;
                    margin-top: 4px;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                    font-size: 18px;
                  }

                  .auth-buttons {
                    display: flex;
                    align-items: center;
                    gap: 1em;
                  }

                  .auth-buttons a {
                    background-color: #ececf1;
                    color: #353740;
                  }
                `}
              </style>
            </div>
          )}
        </div>
      </main>
    </>
  );
}
