import React from "react";
import Head from "next/head";
import styles from "@/styles/index.module.css";
import { useMediaQuery } from "@mui/material";
import { useUser } from "@auth0/nextjs-auth0/client";
import UnauthenticatedScreen from "../components/Shared/UnauthenticatedScreen";
import { Playground } from "../components/Playground";
import { FullscreenNavMenu, MobileNavMenu } from "../components/Navigation";

export default function Index() {
  const { user, error, isLoading } = useUser();
  const isOnMobileScreen = useMediaQuery("(max-width: 649px)");
  const [openNavMenu, setOpenNavMenu] = React.useState(false);

  const handleCloseNavMenu = (event: {}, reason: "backdropClick" | "escapeKeyDown") => {
    setOpenNavMenu(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.appWrapper}>
          <FullscreenNavMenu isAuthenticated={!!user?.sub} isOnMobileScreen={isOnMobileScreen} setOpenNavMenu={setOpenNavMenu} />
          {!!user?.sub ? <Playground isOnMobileScreen={isOnMobileScreen} /> : <UnauthenticatedScreen />}
        </div>

        {isOnMobileScreen ? <MobileNavMenu openNavMenu={openNavMenu} handleCloseNavMenu={handleCloseNavMenu} /> : <></>}
      </main>
    </>
  );
}
